name: Tests

on:
  push: {}

jobs:
  Tox-On-Push:
    runs-on: Ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bootstrap poetry
        working-directory: ./libs/e-lims-logger
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        working-directory: ./libs/e-lims-logger
        run: |
          [ "$(command -v timeout)" ] || function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
          timeout 10s poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        working-directory: ./libs/e-lims-logger
        run: poetry install

      - name: Check lock file
        working-directory: ./libs/e-lims-logger
        run: poetry check --lock

      - name: Run tox
        working-directory: ./libs/e-lims-logger
        run: poetry run tox
    