name: E-lims Utils CI

on:
  push:
    paths:
      - 'libs/e_lims_instruments/**'
  pull_request:
    paths:
      - 'libs/e_lims_instruments/**'

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'libs/e_lims_instruments'

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install dependencies
      run: |
        cd libs/e_lims_instruments
        poetry install -E tests -E docs

    - name: Linters
      run:  |
        cd libs/e_lims_instruments
        poetry run tox -e linters

  tests:
    runs-on: ubuntu-latest
    needs: linters

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'libs/e_lims_instruments'

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install dependencies
      run: |
        cd libs/e_lims_instruments
        poetry install -E tests -E docs

    - name: Python Tests
      run:  |
        cd libs/e_lims_instruments
        poetry run tox -e py${{ matrix.python }}

  documentation:
    runs-on: ubuntu-latest
    needs: [linters, tests]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'libs/e_lims_instruments'

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install dependencies
      run: |
        cd libs/e_lims_instruments
        poetry install -E tests -E docs

    - name: Documentation
      run:  |
        cd libs/e_lims_instruments
        poetry run tox -e documentation

  build:
    runs-on: ubuntu-latest
    # needs: documentation
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'libs/e_lims_instruments'

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install dependencies
      run: |
        dir
        cd libs/e_lims_instruments
        poetry install -E tests -E docs

    - name: Build
      run:  |
        cd libs/e_lims_instruments
        poetry run tox -e build

    - name: Publish on PyPi
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd libs/e_lims_instruments
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry --version
        poetry config --list
        poetry publish --build
