name: Run Black

on:
  push:
    branches:
      - main

jobs:
  run-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull ghcr.io/fabienmeyer/e-lims:latest
      - name: Run Black
        run: |
          docker run ghcr.io/fabienmeyer/e-lims:latest poetry run black .
      
      - name: Run Ruff
        run: |
          docker run ghcr.io/fabienmeyer/e-lims:latest poetry run ruff check .

      - name: Run Mypy
        run: |
            docker run ghcr.io/fabienmeyer/e-lims:latest poetry run mypy .