name: Run code linting

on:
  push:
    branches:
      - main

jobs:
  run-black:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fabienmeyer/e-lims:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Poetry set vitualenv
        run: |
          poetry env use /app/.venv/bin/python

      - name: Run Black
        run: |
          poetry run black .
      
      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Mypy
        run: poetry run mypy .