name: publish-elims-docker
on:
  push:
    branches:
      - main
    paths:
        - 'Dockerfile'
permissions: write-all
jobs:
  publish-elims-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the elims-docker Docker image
        run: |
          docker build . --tag ghcr.io/fabienmeyer/e-lims:latest
          docker run ghcr.io/fabienmeyer/e-lims:latest
          docker push ghcr.io/fabienmeyer/e-lims:latest