name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run-testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fabienmeyer/elims:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.11.5"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Project initialization:
      - name: Poetry configure and install
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create true
          poetry env use /root/.pyenv/versions/${{ matrix.python-version }}/bin/python
          poetry install

      - name: Run Pytest
        run: |
          poetry run pytest .